version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_SCHEMA: task_system
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}


  crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    container_name: crm
    extra_hosts:
      - "crm:127.0.0.1"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/my_db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - db

