server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: task_system
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  config:
    import: optional:file:.env[.properties]

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: task_system
    out-of-order: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  role:
    default: "ROLE_USER"